name: PyInstaller Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install Dependencies
      shell: pwsh
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      shell: pwsh
      run: |
        pyinstaller --onefile your_script.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: dist/