name: PyInstaller Windows Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.1', '3.2', '3.3', '3.4', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      shell: pwsh
      run: |
        cd Supervisor
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pyinstaller CoreInsight.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoreInsight-${{ matrix.python-version }}.exe
        path: Supervisor/dist/CoreInsight.exe
