name: PyInstaller Windows Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      shell: pwsh
      run: |
        cd Supervisor
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pyinstaller CoreInsight.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CoreInsight.exe
        path: Supervisor/dist/CoreInsight.exe
